### PR TITLE
Update docs about Replicator to mention shuttle

### PR DESCRIPTION
**Pull request by sds**
## PR-Codex overview
The focus of this PR is to update the replication app documentation, replacing references to Hubble with Shuttle and simplifying installation instructions.

### Detailed summary
- Replaced references to Hubble with Shuttle throughout the document.
- Simplified installation instructions by removing the script and Docker setup details.
- Removed specific querying and schema details, directing users to the documentation for more information.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by PengDeng-Cyber** [comment]
Wondering why the replicator is deprecated? Looks the structured data is more useful for devs. But the shuttle is replicating data that are not direct-usable. Do you have any context or documents that I can read and learn? Thanks! @sds

**Comment by sds** [comment]
The Replicator had numerous bugs which were difficult to address given its design. We also weren't using the Replicator ourselves, which lead to users reporting bugs that didn't affect us.

Shuttle addresses this by being something we actually use in our own infrastructure. If it works for Warpcast, it should work for you.

>But the shuttle is replicating data that are not direct-usable

Can you provide an example? Not sure I understand.

**Comment by PengDeng-Cyber** [comment]
Thank you for your reply! `not direct-usable` means the Replicator will generate tables described in this doc: https://docs.farcaster.xyz/reference/replicator/schema including a table named `reactions`. But the shuttle only generates 3 tables and most of the contents are embedded as JSON format in `messages` table. So it's not direct usable as `reactions`. Do you have some other data pipeline to decode the body to settle it down to different tables?

**Comment by PengDeng-Cyber** [comment]
Furthermore, My Shuttle will hang in worker / backfill mode

**Comment by sds** [comment]
Sorry for the delay in response. Thanks for clarifying what you were looking for.

The reason we don't include all the derived tables like `casts`, `reactions`, etc. is because the information stored in those tables—along with how they are indexed—is very specific to your application's needs. For us to provide a schema for all derived data would be making assumptions about everyone's application architecture, which quickly makes the tool generally useful for no one. 

Instead, we've provided building blocks that allow you to create data yourself with the schema you desire.

You raise a good point about the docs referencing the old Replicator. We should remove these to avoid further confusion.

**Pull request merged**
